name: compile

permissions:
  contents: write

on: 
  push:
    tags:
      - "v*"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repo
        uses: actions/checkout@v2
      - name: Run makefile to compile LaTeX
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            apk add font-liberation
            make example 
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/Beispiel.pdf
